baseURL = "https://technicalsourcery.net/"
languageCode = "en-us"
author = "Karl Stenerud"
title = "Technichal Sourcery"
#canonifyurls = true
paginate = 3
theme = "aether"

[params]
brand = "Technical SOURCEry"
description = "Drawing back the curtain"
# bgimg = "URL to the image used for the page background - optional"
