baseURL = "https://technicalsourcery.net/"
languageCode = "en-us"
author = "Karl Stenerud"
title = "Technichal Sourcery"
#canonifyurls = true
paginate = 3
theme = "aether"
googleAnalytics = "UA-137565314-1"
disqusShortname = "technical-sourcery"

[params]
brand = "Technical SOURCEry"
description = "Technical oddities for software developers"
authorDescription = "I'm a software engineer with over 20 years as a professional in the industry. My extensive and unique experiences spans four countries, covering everything from embedded systems to enterprise services."
authorImage = "avatar.jpg"
# bgimg = "URL to the image used for the page background - optional"
github = "https://github.com/kstenerud"
email = "kstenerud@gmail.com"
linkedin = "https://www.linkedin.com/in/kstenerud"
authorTitle = "Software Professional"
author = "Karl Stenerud"
